# ========== Worker 基本配置 ==========
name = "lottery-tracking"
main = "worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

# ========== KV 命名空间绑定 ==========
[[kv_namespaces]]
binding = "MY_KV"
id = "277638f83f6b4e9a851c53238a5668fb"
preview_id = "277638f83f6b4e9a851c53238a5668fb"

# ========== 环境变量 ==========
[vars]
ENVIRONMENT = "production"