name = "lottery-tracking"
main = "worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "MY_KV"
id = "277638f83f6b4e9a851c53238a5668fb"
preview_id = "277638f83f6b4e9a851c53238a5668fb"

[vars]
ENVIRONMENT = "production"
ADMIN_KEY = "zft11456662011"  # 你的管理员密码